service: ${self:custom.subsys}-event-lake-es

provider:
  name: aws
  deploymentBucket: ${file(serverless/cfn.yml):deploymentBucket}
  iam:
    deploymentRole: ${file(serverless/cfn.yml):deploymentRole}
  stackTags: ${file(serverless/tags.yml)}

params: ${file(serverless/config.yml):params}
custom:
  partition: aws # aws-us-gov
  org: my
  subsys: subsys1
  elasticsearch:
    retentionDays: 40

plugins:
  - elasticsearch # create template (local plugin)

resources:
  - ${file(serverless/oss.yml):resources}
  - ${file(serverless/s3.yml):resources}
  - ${file(serverless/firehose.yml):resources}
