service: ${self:custom.subsys}-event-hub

provider:
  name: aws
  # deploymentBucket: ${file(serverless/cfn.yml):deploymentBucket}
  # iam:
  #   deploymentRole: ${file(serverless/cfn.yml):deploymentRole}
  stackTags: ${file(serverless/tags.yml)}

params: ${file(serverless/config.yml):params}

custom:
  partition: aws # aws-us-gov
  org: my
  subsys: subsys1
  # global: ${file(serverless/global.yml):global}

resources:
  - ${file(serverless/bus.yml):resources}
  # - ${file(serverless/cw.yml):resources}
  # - ${file(serverless/schema.yml):resources}
  # - ${file(serverless/global.yml):resources}
  # - ${file(serverless/kinesis.yml):resources}
  # - ${file(serverless/ingress.yml):resources}
  # - ${file(serverless/egress.yml):resources}
  # - ${file(serverless/conditions.yml)}
