name: 4 - CD - Production - East - Manual Only

# manually deploy to the remaining regions after the regional canary deployment is certified

on:
  workflow_dispatch: # manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      # test against dev
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
      - run: npm test
      - run: npm run test:int
      # deploy to prod
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.PRD_AWS_ROLE }}
      - run: npm run dp:prd:e

