service: ${self:custom.subsys}-event-metrics

provider:
  name: aws
  deploymentBucket: ${self:custom.org}-${self:custom.subsys}-sls-deploy-${opt:stage}-${opt:region}
  iam:
    deploymentRole: arn:${self:custom.partition}:iam::${aws:accountId}:role/cfnRole-${opt:stage}
    role: ${file(serverless/iam.yml):role}
  stackTags: ${file(serverless/tags.yml)}
  runtime: nodejs16.x
  logRetentionInDays: 30
  environment: ${file(serverless/config.yml):environment}

params: ${file(serverless/config.yml):params}
package:
  individually: true
custom:
  partition: aws # aws-us-gov
  org: my
  subsys: subsys1
  webpack:
    includeModules: true

plugins:
  - serverless-webpack
  - baton-vcr-serverless-plugin
  - serverless-offline

functions:
  listener:
    handler: src/listener/index.handle
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ ListenerQueue, Arn ]

resources:
  - ${file(serverless/sqs-listener.yml):resources}
  - ${file(serverless/cw.yml):resources}
  - ${file(serverless/conditions.yml)}
