resources:
  Resources:
    ListenerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${opt:stage}-listener
        # KmsMasterKeyId: alias/aws/sqs
        # https://stackoverflow.com/questions/63808647/aws-forward-event-bridge-event-to-encrypted-sqs-amazon-managed-key

    ListenerQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: ListenerQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sqs:SendMessage
              Resource:
                Fn::GetAtt: [ ListenerQueue, Arn ]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Fn::GetAtt: [ EventRule, Arn ]
  
    EventRule: 
      Type: AWS::Events::Rule
      Properties: 
        EventBusName: ${cf:${self:custom.subsys}-event-hub-${opt:stage}.busName}
        EventPattern: 
          source:
            - anything-but: nothing # all
        State: ENABLED
        Targets: 
          - Id: Channel
            Arn: 
              Fn::GetAtt: [ ListenerQueue, Arn ]
            InputPath: $.detail

  Outputs:
    ListenerQueue:
      Value:
        Ref: ListenerQueue
