resources:
  Resources:
    LogGroupEvents: 
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 30
        LogGroupName: /aws/events/${self:service}-${opt:stage}-events
        # KmsKeyId: 
    LogGroupFaults: 
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 30
        LogGroupName: /aws/events/${self:service}-${opt:stage}-faults
        # KmsKeyId: 

    # ----------
    # POLICIES
    # ----------

    LogRole:
      Type: AWS::IAM::Role
      Properties:
        PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${aws:accountId}:policy/${self:custom.subsys}-ServerlessRuntimeBoundary-${opt:stage}'
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${opt:stage}-log
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - Fn::GetAtt: [ LogGroupEvents, Arn ]
                    - Fn::GetAtt: [ LogGroupFaults, Arn ]

    # ----------
    # RULES
    # ----------

    LogRuleEvents:
      Type: AWS::Events::Rule
      Properties:
        EventBusName:
          Ref: Bus
        EventPattern:
          detail:
            type:
              - anything-but: fault
        State: ENABLED
        RoleArn:
          Fn::GetAtt: [ LogRole, Arn ]
        Targets:
          - Id: LogEvents
            Arn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupEvents}'

    LogRuleFaults:
      Type: AWS::Events::Rule
      Properties:
        EventBusName:
          Ref: Bus
        EventPattern:
          detail:
            type: 
              - fault
        State: ENABLED
        RoleArn:
          Fn::GetAtt: [ LogRole, Arn ]
        Targets:
          - Id: LogFaults
            Arn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupFaults}'
